packageExtensions:
  "eslint-plugin-flowtype@*":
    dependencies:
      "@babel/plugin-syntax-flow": "^7.14.5"
      "@babel/plugin-transform-react-jsx": "^7.14.9"
  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": ">=7.21.4"
  "@babel/plugin-syntax-flow@*":
    dependencies:
      "@babel/core": "^7.0.0-0"
  "@babel/plugin-syntax-jsx@*":
    dependencies:
      "@babel/core": "^7.0.0-0"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "^7.0.0-0"
